# Generated by Django 4.1.4 on 2022-12-09 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_product_grow_pot_size_product_height_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="grow_pot_size",
        ),
    ]
